package itesm.rieti.model.enums

enum class Municipio
{
    ATIZAPAN, NAUCALPAN, CUAUTITLAN_IZCALLI, CUAUTITLAN,
    HUIXQUILUCAN, NICOLAS_ROMERO, TLALNEPANTLA, TULTITLAN,
    COACALCO, ECATEPEC, NEZAHUALCOYOTL
}