package itesm.rieti.model.enums

enum class Municipio
{
    ATIZAPAN, NAUCALPAN, CUAUTITLAN_IZCALLI, CUAUTITLAN,
    HUIZQUILUCAN, NICOLAS_ROMERO, TLALNEPANTLA, TULTITLAN,
    COACALCO, ECAPTEPEC, NEZAHUALCOYOTL
}